# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZGy-GESst_i8Tjlkva5cph_v97p2YDQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Resume Builder")
# st.write("Build your professional resume easily.")
# 
# st.header("Main Content")
# st.write("This is where the main sections for building your resume will go.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Resume Builder")
# st.write("Build your professional resume easily.")
# 
# st.header("Personal Information")
# name = st.text_input("Full Name", key="full_name")
# email = st.text_input("Email Address", key="email")
# phone = st.text_input("Phone Number", key="phone")
# linkedin = st.text_input("LinkedIn Profile URL", key="linkedin")
# github = st.text_input("GitHub Profile URL", key="github")
# summary = st.text_area("Professional Summary", key="professional_summary")
# 
# 
# st.header("Education")
# education_degree = st.text_input("Degree", key="education_degree")
# education_major = st.text_input("Major", key="education_major")
# education_institution = st.text_input("Institution", key="education_institution")
# education_year = st.text_input("Graduation Year", key="education_year")
# 
# 
# st.header("Experience")
# experience_title = st.text_input("Job Title", key="experience_title")
# experience_company = st.text_input("Company", key="experience_company")
# experience_years = st.text_input("Years of Experience", key="experience_years")
# experience_description = st.text_area("Job Description / Responsibilities", key="experience_description")
# 
# 
# st.header("Skills")
# skills_list = st.text_area("List your skills (comma-separated)", key="skills_list")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Resume Builder")
# st.write("Build your professional resume easily.")
# 
# st.header("Personal Information")
# name = st.text_input("Full Name", key="full_name")
# email = st.text_input("Email Address", key="email")
# phone = st.text_input("Phone Number", key="phone")
# linkedin = st.text_input("LinkedIn Profile URL", key="linkedin")
# github = st.text_input("GitHub Profile URL", key="github")
# summary = st.text_area("Professional Summary", key="professional_summary")
# 
# 
# st.header("Education")
# education_degree = st.text_input("Degree", key="education_degree")
# education_major = st.text_input("Major", key="education_major")
# education_institution = st.text_input("Institution", key="education_institution")
# education_year = st.text_input("Graduation Year", key="education_year")
# 
# 
# st.header("Experience")
# experience_title = st.text_input("Job Title", key="experience_title")
# experience_company = st.text_input("Company", key="experience_company")
# experience_years = st.text_input("Years of Experience", key="experience_years")
# experience_description = st.text_area("Job Description / Responsibilities", key="experience_description")
# 
# 
# st.header("Skills")
# skills_list = st.text_area("List your skills (comma-separated)", key="skills_list")
# 
# st.header("Generated Resume")
# 
# # Access user inputs from session_state
# full_name = st.session_state.get('full_name', '')
# email = st.session_state.get('email', '')
# phone = st.session_state.get('phone', '')
# linkedin = st.session_state.get('linkedin', '')
# github = st.session_state.get('github', '')
# professional_summary = st.session_state.get('professional_summary', '')
# education_degree = st.session_state.get('education_degree', '')
# education_major = st.session_state.get('education_major', '')
# education_institution = st.session_state.get('education_institution', '')
# education_year = st.session_state.get('education_year', '')
# experience_title = st.session_state.get('experience_title', '')
# experience_company = st.session_state.get('experience_company', '')
# experience_years = st.session_state.get('experience_years', '')
# experience_description = st.session_state.get('experience_description', '')
# skills_list = st.session_state.get('skills_list', '')
# 
# 
# # Format the collected information into a readable resume structure using Markdown
# resume_content = f"""
# # {full_name}
# 
# **Contact Information**
# *   Email: {email}
# *   Phone: {phone}
# *   LinkedIn: {linkedin}
# *   GitHub: {github}
# 
# ## Professional Summary
# {professional_summary}
# 
# ## Education
# **{education_degree} in {education_major}**
# {education_institution}, {education_year}
# 
# ## Experience
# **{experience_title}** at {experience_company} ({experience_years} years)
# {experience_description}
# 
# ## Skills
# {skills_list}
# """
# 
# # Display the generated resume
# st.markdown(resume_content)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Resume Builder")
# st.write("Build your professional resume easily.")
# 
# st.header("Personal Information")
# name = st.text_input("Full Name", key="full_name")
# email = st.text_input("Email Address", key="email")
# phone = st.text_input("Phone Number", key="phone")
# linkedin = st.text_input("LinkedIn Profile URL", key="linkedin")
# github = st.text_input("GitHub Profile URL", key="github")
# summary = st.text_area("Professional Summary", key="professional_summary")
# 
# 
# st.header("Education")
# education_degree = st.text_input("Degree", key="education_degree")
# education_major = st.text_input("Major", key="education_major")
# education_institution = st.text_input("Institution", key="education_institution")
# education_year = st.text_input("Graduation Year", key="education_year")
# 
# 
# st.header("Experience")
# experience_title = st.text_input("Job Title", key="experience_title")
# experience_company = st.text_input("Company", key="experience_company")
# experience_years = st.text_input("Years of Experience", key="experience_years")
# experience_description = st.text_area("Job Description / Responsibilities", key="experience_description")
# 
# 
# st.header("Skills")
# skills_list = st.text_area("List your skills (comma-separated)", key="skills_list")
# 
# st.header("Generated Resume")
# 
# # Access user inputs from session_state
# full_name = st.session_state.get('full_name', '')
# email = st.session_state.get('email', '')
# phone = st.session_state.get('phone', '')
# linkedin = st.session_state.get('linkedin', '')
# github = st.session_state.get('github', '')
# professional_summary = st.session_state.get('professional_summary', '')
# education_degree = st.session_state.get('education_degree', '')
# education_major = st.session_state.get('education_major', '')
# education_institution = st.session_state.get('education_institution', '')
# education_year = st.session_state.get('education_year', '')
# experience_title = st.session_state.get('experience_title', '')
# experience_company = st.session_state.get('experience_company', '')
# experience_years = st.session_state.get('experience_years', '')
# experience_description = st.session_state.get('experience_description', '')
# skills_list = st.session_state.get('skills_list', '')
# 
# 
# # Format the collected information into a readable resume structure using Markdown
# resume_content = f"""
# # {full_name}
# 
# **Contact Information**
# *   Email: {email}
# *   Phone: {phone}
# *   LinkedIn: {linkedin}
# *   GitHub: {github}
# 
# ## Professional Summary
# {professional_summary}
# 
# ## Education
# **{education_degree} in {education_major}**
# {education_institution}, {education_year}
# 
# ## Experience
# **{experience_title}** at {experience_company} ({experience_years} years)
# {experience_description}
# 
# ## Skills
# {skills_list}
# """
# 
# # Display the generated resume
# st.markdown(resume_content)
# 
# # Add a download button for the generated resume
# st.download_button(
#     label="Download Resume",
#     data=resume_content,
#     file_name="resume.md",
#     mime="text/markdown",
# )

# Read the content of app.py
with open('app.py', 'r') as f:
    app_content = f.read()

# Identify imported libraries (basic approach)
# This is a simple approach and might not catch all cases (e.g., conditional imports)
imported_libraries = set()
for line in app_content.splitlines():
    if line.strip().startswith('import '):
        parts = line.strip().split()
        if len(parts) > 1:
            imported_libraries.add(parts[1].split('.')[0])
    elif line.strip().startswith('from '):
        parts = line.strip().split()
        if len(parts) > 1:
            imported_libraries.add(parts[1].split('.')[0])

# Read the content of requirements.txt
try:
    with open('requirements.txt', 'r') as f:
        requirements_content = f.read()
    required_libraries = set([line.strip().split('==')[0] for line in requirements_content.splitlines() if line.strip() and not line.strip().startswith('#')])
except FileNotFoundError:
    required_libraries = set()

# Find missing libraries
missing_libraries = imported_libraries - required_libraries

# Add missing libraries to requirements.txt
if missing_libraries:
    with open('requirements.txt', 'a') as f:
        for lib in missing_libraries:
            f.write(f"\n{lib}")

print("Libraries in app.py:", imported_libraries)
print("Libraries in requirements.txt:", required_libraries)
print("Missing libraries added to requirements.txt:", missing_libraries)